### PR TITLE
Input-parsing and validation

### PR DESCRIPTION
**Pull request by DeveloperMarius**
Evening,
Hello @skipperbent,

after my PRs #497 and #519 are still not included into the main project, I would like to intoduce an what I think is a "better" method of allowing users like me customize their InputHandler to their own needs.

### Input Handler

I created an example InputHandler for this PR in https://github.com/DeveloperMarius/router-input-handler-plugin (Not ready for a release, just a short example).

You could easily include your own InputHandler using:
```
$request = new \Pecee\Http\Request();
$request->setInputHandler(new InputHandler());
SimpleRouter::setRequest($request);

$inputHandler = SimpleRouter::request()->getInputHandler();
```
Normal users wouldn't recognice a difference.

**But** i would preferr integrating [my InputHandler](https://github.com/DeveloperMarius/router-input-handler-plugin/blob/main/src/InputHandler/InputHandler.php). But this InputHandler would come with breaking changes. Maybe integrate it into v5 of the router.

### Input Validation

Now you can validate inputs by adding the following code to the route:
```
TestRouter::get('/my/test/url', 'DummyController@method3')
            ->validateInputs([
                    'username' => 'string|max:50',
                    'password' => 'string|max:20',
                    'remember_me' => 'integer|range:0,1'
            ]);
```
or using a more OOP way:
```
TestRouter::get('/my/test/url', 'DummyController@method3')
            ->validateInputs(
                InputValidator::make()
                      ->add(InputValidatorItem::make('username')->isString()->max(50))
                      ->add(InputValidatorItem::make('password')->isString()->max(20))
            );
```
or validate inside the controller function:
```
$request->validate(
    InputValidator::make()
        ->add(InputValidatorItem::make('username')->isString()->max(50))
        ->add(InputValidatorItem::make('password')->isString()->max(20))
);
```

Additional you can use **custom rules** by providing the full classname:
```
TestRouter::get('/my/test/url', 'DummyController@method3')
            ->validateInputs([
                'customParam' => 'Dummy\InputValidatorRules\ValidatorRuleCustom'
            ]);
```
or by defining a **namespace** for custom rules:
```
InputValidator::setCustomValidatorRuleNamespace('Dummy\InputValidatorRules');
TestRouter::get('/my/test/url', 'DummyController@method3')
            ->validateInputs([
                'customParam' => 'custom'
            ]);
```
For custom validator rules in a namespace, please name the classes `ValidatorRule<rulename>` where the rulename have to be in camel case.
You can provide multiple attributes to the rule functions using the following syntax: `<rule1>|<rule2>:<attr1>|<rule3>:<attr1>,<attr2>`.

### My todo:
- [x] Fix RegEx multiple attributes
- [x] Better handling of Error Messages + getter
- [x] Better formatting of Error Messages
- [x] Transfer validator messages from https://github.com/DeveloperMarius/router-input-handler-plugin
- [x] Parse validator rule tag in camel case from `word_word` to `WordWord` to allow Classnames like `ValidatorRuleStartsWith` (Tag would be `starts_with`)
- [ ] README
- [x] Email @skipperbent to ask him to review the PRs
- [ ] Allow input keys like `parentkey.childkey` when parsing for example json data. This would be more easy with my InputHandler in my [InputItem](https://github.com/DeveloperMarius/router-input-handler-plugin/blob/main/src/InputHandler/IIInputItem.php) because there is the method `getInputItems()` which would make it access them way more easily. 

Referring to the last bullet point, I am currently thinking about throwing the custom InputHandler thing away and just implement [mine](https://github.com/DeveloperMarius/router-input-handler-plugin/blob/main/src/InputHandler/InputHandler.php). What do you think?

When someone is interested in features, let me know!
When someone wants to work on a point, let me know so that we don't work on the same one. After that please create a fork of [my fork](https://github.com/DeveloperMarius/simple-php-router/tree/inputhandler-plugin) and create a PR in my fork. I will then take a look and merge it into this PR here.
I would like to hear your feedback @skipperbent.

~ Marius

### CODE REVIEW

**Comment by guiiamorim** [comment]
Hello @DeveloperMarius, @skipperbent 

I cloned your repo and I also couldn't reproduce any of the errors you mentioned about the middleware.

About the plugin, I loved the idea to create a separate input handler to put your own validation logic, but I think that we could do something even better, by allowing the developer to create handlers per request, something on the lines of this package: https://github.com/LinioIT/input.

That way, we could have a set of handlers that we could apply directly on the route, the same way we define the middlewares, like: 

`
SimpleRouter::group([], function () {
    SimpleRouter::post('/my/test/url', function(){
        echo 'Success Content' . PHP_EOL;
    }, ['middleware' => TestMiddleware::class, 'inputHandler' => MyInputHandler::class]);
});
`

Doing like this would allow us to have all the rules set on the route by default and would simply have to call a validate method on the input handler of the request, or we colud even reject the request altogether before even hitting the controller for the route.

At the moment I don't have a concrete idea of how we could accomplish this, but if you guys find the idea interesting I could try and develop a PR for this.

Putting it all together what I'm proposing is something like this:

`
    class MyInputHandler {
      
          public function create(): array
          {
              return [
                  'username' => function(InputItem $value) {
                      return $value->validate()->require()->minLength(2)->maxLength(20)->isString()->valid();
                  },
                  'password' => function(InputItem $value) {
                      return $value->validate()->require()->minLength(8)->maxLength(20)->valid();
                  },
              ];
          }
      
      }
      
      SimpleRouter::group([], function () {
          SimpleRouter::post(
              '/my/test/url', 
              'AuthController@login', 
              ['middleware' => TestMiddleware::class, 'inputHandler' => MyInputHandler::class]
          );
      });
      
      class AuthController {
          public function login()
          {
              $validatedInput = SimpleRouter::request()->input()->validate();
      
              // Do something with the data
          }
      }
`

**Comment by DeveloperMarius** [comment]
Hello @guiiamorim,
thank you for your reply and for testing the middleware issue.

I like the idea, but I think it would be too time-intensive to parse the inputs for every group with a different InputHandler, don't you think?
Also, what do you want to change in the behaviour of parsing inputs in the InputHandler between one group and another?
I think what you want is that you can validate inputs for all routes in a group, but the way I see it, you can already do this using a Middleware:
```
class TestMiddleware implements IMiddleware
{
    public function handle(Request $request) : void
    {
        inputHandler()->requireParameters(array(
            'userId' => function(InputItem $value){
                return $value->validate()->require()->isInteger()->valid();
            }
        ));
    }
}
```
and apply it to the group:
```
SimpleRouter::group(['middleware' => TestMiddleware::class], function () {
[...Routes...]
});
```
Or do I understand something wrong?
Thank you for your interest!

~ Marius

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius,

Maybe it would be a bit time-intensive to do this, as I said before I still don't have a strategy to approach this idea, maybe we could try and discuss a bit more.

I think my example was a bit confusing, but what I thought was for a handler per route, not for a group. Say you have a form to register a product. For this form you would create a handler to validate this request and attach to the route. It would be something similar to Laravel's FormRequest, with the difference that in Laravel the request goes directly on the controller method.

I suggested this approach because Ithink it would be more cleaner, since the way your package handles the validation logic is more verbose than Laravel's and a few other packages that I found on github.

That said, adding another package just for handling validation would increase a bit more the size of the application in comparisson to your alternative, so even if you don't thik is worth the time to accomplish this, I'm still interested in using your approach, and would love to contribute in any way if you need.

**Comment by DeveloperMarius** [comment]
Hey,

I didn't ment the time to code this approach, I ment the time the runtime needs to run through etc. But you ment the Validation not the parser of the inputs, so ignore my comment on that.

I think it is a great idea to add a InputValidator to the route. In my last commit I implemented this like a middleware but after pushing I thought maybe it would be better to just referr to a method then to a whol class, don't you think?
A whol class for one route is far to much...

But what do you think of the implementation of your idea?

~ Marius

**Comment by DeveloperMarius** [comment]
🎉🎉🎉
I fixed the PHPUnit error
🎉🎉🎉

**Comment by guiiamorim** [comment]
Hello @DeveloperMarius ,

I agree that a whole class per request is kinda too much, but I think that the verbosity of the validation method you used will generate too much noise on the controllers / functions that validate inputs.

Maybe we could try an approach like Laravel then, and parse an array of rules/messages to construct the validation, maybe it would be even better than my suggestion.

About my implementation, I have to get a bit more time to have a concrete idea of how to accomplish this, but as far as got in the code I think it would not be much trouble, we could just verify if the `inputHandler` setting is present on the route and attach it to the request. Then, the developer would simply call a validate method on the controller / function to see if the request is valid.

Let me know what you think about the two approaches I listed and if you find it interesting I can try and put together a PR for this.

**Comment by guiiamorim** [comment]
Hey @DeveloperMarius ,

I really liked this implementation, this solves both problems with our original strategies. I'm kinda busy right now, but maybe tonight (I'm from Brazil) I can take a look on your code and RegEx so we can put this to work.

It would be interesting if we could do something like this also:

`$request->validate(
    InputValidator::make()
        ->validateInputs([
            'username' => 'string|max:50',
            'password' => 'string|max:20'
        ])
);`

But if it's too much trouble we can leave as is.

Waiting to hear your thoughts and instructions about what can I do to help.

**Comment by DeveloperMarius** [comment]
Hey @guiiamorim,

you can already add multipe "ValidatorItems". Thats because it is an array 😉.
You can do both:
```
$request->validate(
    InputValidator::make()
        ->validateInputs([
            'username' => 'string|max:50',
            'password' => 'string|max:20'
        ])
);
```
and
```
$request->validate(
    InputValidator::make()
        ->add(InputValidatorItem::make('username')->isString()->max(50))
        ->add(InputValidatorItem::make('password')->isString()->max(20))
);
```

I also added support for custom rules in the last commit.
You can add custom rules by providing the full path to the class or first set an namespace and then just use the tag:
```
InputValidator::setCustomValidatorRuleNamespace('Dummy\InputValidatorRules');
TestRouter::get('/my/test/url', 'DummyController@method3')
            ->validateInputs([
                'customParam' => 'custom'
            ]);
```
or
```
TestRouter::get('/my/test/url', 'DummyController@method3')
            ->validateInputs([
                'customParam' => 'Dummy\InputValidatorRules\ValidatorRuleCustom'
            ]);
```

Note: I adjusted the RegEx to `/([a-zA-Z\\\\=\/<>]+)(?::([a-z-A-Z0-9=<>]+))*/`.
Watch out for the four Backslashs, explained on [StackOverflow](https://stackoverflow.com/questions/11044136/right-way-to-escape-backslash-in-php-regex/15369828#answer-15369828).

My todo:
- [ ] Fix RegEx multiple attributes
- [ ] Better handling of Error Messages + getter
- [ ] Better formatting of Error Messages
- [ ] Transfer validator messages from https://github.com/DeveloperMarius/router-input-handler-plugin
- [ ] Parse validator rule tag in camel case from `word_word` to `WordWord` to allow Classnames like `ValidatorRuleStartsWith` (Tag would be `starts_with`)
- [ ] Allow input keys like `parentkey.childkey` when parsing for example json data. This would be more easy with my InputHandler in my [InputItem](https://github.com/DeveloperMarius/router-input-handler-plugin/blob/main/src/InputHandler/IIInputItem.php) because there is the method `getInputItems()` which would make it access them way more easily. 

Referring to the last bullet point, I am currently thinking about throwing the custom InputHandler thing away and just implement mine. What do you think?

When you want to work on a point, just let me know so that we don't work on the same one.
I don't know what the best way is to do that, but [this article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork) explains it, I think.

Which features do you want to add?
Btw. I am from Germay, so we have a 4 hour difference.
Looking forward to working with you.

~ Marius

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius,

> you can already add multipe "ValidatorItems". Thats because it is an array 😉.
You can do both:

Sorry, I didn't catch that we could do both ways by seeing your example.

> Referring to the last bullet point, I am currently thinking about throwing the custom InputHandler thing away and just implement mine. What do you think?

I think it's better to just implement yours, if @skipperbent is ok with it.

> When you want to work on a point, just let me know so that we don't work on the same one.
I don't know what the best way is to do that, but [this article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork) explains it, I think.

I guess that this way is fine, I don't know the best way either. Let me know if I have permission already to commit to the PR and I will start working.

> Which features do you want to add?
Btw. I am from Germay, so we have a 4 hour difference.
Looking forward to working with you.

For now, nothing comes to mind, if I see something that I think is missing I'll let you know. I will start by working with the RegEx then, is something that I'm sort of good at.
Glad to be able to help.

**Comment by DeveloperMarius** [comment]
Perfect. I will look out for permissions tomorrow (it's currently like 2am).
But you can already clone the branch, I think.

~ Marius

**Comment by DeveloperMarius** [comment]
Morning @guiiamorim,
I don't know why, but I could not invite you as a collaborator or give you any special permissions.
I think it is the best when you just create a fork of [my fork](https://github.com/DeveloperMarius/simple-php-router) and then create a normal PR to my [inputhandler-plugin branch](https://github.com/DeveloperMarius/simple-php-router/tree/inputhandler-plugin).
After that I can then merge your PR into my PR. This is a bit confusing, but I think this is the best way.

~ Marius

**Comment by guiiamorim** [comment]
Morning @DeveloperMarius,

I'll do that then, as soon as I have a bit of time here I'll give a try on the RegEx.

**Comment by DeveloperMarius** [comment]
Perfect, thank you!

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius,

I couldn't make a PR yesterday to your repository, I guess you need to grant me permission.

Unfortunately, I didn't manage to make the RegEx return all parameters from the parameters, it only returns the last one, I found [this](https://www.php.net/manual/en/function.preg-match-all.php) on the PHP docs, but doesn't fit our case, so I'm guessing is a bug with PHP:

> If the pattern contains duplicate named subpatterns, only the rightmost subpattern is stored in $matches[NAME]. 

So I decided to resolve this issue with PHP, I ajusted the RegEx to parse parameters with space and then grabbed the hole match and separated the attributes manually. I also changed the parametters separator to "," as I think is more intuitive and clear. This is the solution I came to:
```PHP
public function parseSettings(string $settings){
        $matches = array();
        //Add "\\\\" to allow one Backslash
        //https://stackoverflow.com/questions/11044136/right-way-to-escape-backslash-in-php-regex/15369828#answer-15369828
        //I changed the RegEx to include strings with spaces and changed the params separator to ','
        preg_match_all('/([a-zA-Z\\\\=\/<>]+)(?::?([a-z-A-Z0-9=<>\s]+,?))*/', $settings, $matches);
        for($i = 0; $i < sizeof($matches[0]); $i++){
            $tag = $matches[1][$i];
            $attributes = explode(':', $matches[0][$i]);
            $attributes = sizeof($attributes) < 2 ? array() : explode(',', $attributes[1]);

            $this->addRuleByTag($tag, $attributes);
        }
    }
```

Since I could not make a PR, feel free to add any comments on this so I can review my code before sending the PR. Also, I noticed something on your code: it doesn't distinguish the methods separator, so the string `'string:22|max:200|min:11:11|notNull:1'` is the same as `'string:22*max:200*min:11:11*notNull:1'`. I don't think it's a good approach to leave anything be a separator, but if you have a reason to do so, please let me know.

**Comment by DeveloperMarius** [comment]
Hey,

yes, please fork my fork and then create a branch from which you will then create an PR to my fork. A bit complicated, I know xD

I like your approach using , as the seperator. Using PHP we can then split on the `,` but allow `\,` as a normal character for `,`. Could you do this?
I changed your RegEx a bit, so we have `$matches[1]` all rules and `$matches[2]` all attributes in one string which you then can split using PHP.
`/([a-zA-Z\\\\=\/<>]+)(?::([a-z-A-Z0-9=<>\+.%\?\!:,\s\*&\-\/\\\\]+)*)?\|?/`
So the input `string:22,11|max:200,ab?!:|min:11:11` results in
```
[
    [
        "string:22,11|",
        "max:200,ab?!:|",
        "min:11:11"
    ],
    [
        "string",
        "max",
        "min"
    ],
    [
        "22,11",
        "200,ab?!:",
        "11:11"
    ]
]
```
You can see it working [here](https://regex101.com/r/ycA5me/2).
Yes we have the problem with the `|`. The point is that we are using a "whitelist" for all allowed chars and chars that are not in the RegEx are excluded. I think you can see the result [here](https://regex101.com/r/wnbG1X/1). When you have a better idea, please let me know.

What do you think?
I am very busy this weekend, so I think I will have to time to code on the PR itself, but still can write with you etc.
When you created the PR, i will merge it into mine.

~ Marius

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius.

> The point is that we are using a "whitelist" for all allowed chars and chars that are not in the RegEx are excluded. I think you can see the result [here](https://regex101.com/r/wnbG1X/1). When you have a better idea, please let me know.

I updated the [RegEx](https://regex101.com/r/wnbG1X/2) so instead of having a whitelist of characters we have a blocklist, so the methods separators can't be in the parameters, but anything else can.

If there's some characters that may be dangerous to have in the parameters we can just block, I think it's a better solution (shorter and easier to read). If this change is ok I will make the fork and PR later today and we can start the other items on the todo.

> I have to add that we can tell developers to watch out to the allowed chars and tell them that they should follow our structure.

Yes, every other validation package I looked have some structure that the developer have to follow, ours can be the same.

**Comment by DeveloperMarius** [comment]
Good Idea,
could you integrate that the characters in the block list are allowed when they have a preceding `\`? I think we could do this using a look behind.

I don't think that we should disallow other specific chars. I mean these are just attributes that are defined by the developers and no end users.

You can create the PR and when I think something should be changed, we can talk in the PR chat.

Thank you for your help!

~ Marius

**Comment by guiiamorim** [comment]
Ok then, I will update my code and tonight will make the PR

**Comment by DeveloperMarius** [comment]
Hey,

no, feel free to copy all validation rules from my validator to this PR. 
Pull the branch first, because I changed some things.
Thanks.

~ Marius

**Comment by DeveloperMarius** [comment]
Hey @guiiamorim,

how is it going?

~ Marius

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius,

Sorry for the delay, this week we found a bug in our software that took me too long to solve.

I'm migrating some of the rules right now and maybe tomorrow it will be all done, maybe I can even add some rules if I have the time.

**Comment by DeveloperMarius** [comment]
Hey,

no problem. Perfect, take your time.

~ Marius

**Comment by guiiamorim** [comment]
Hey @DeveloperMarius ,

I'm working on the rules right now and I did some changes to the `InputValidatorItem` class, resolving the problem with snake case on the tag adn replacing the rule methods on the class for a magic method call, which calls the `addRuleByTag` method. The result is this:

```PHP
/**
     * @param string $rule - Rule Tag or Classname
     * @param array $attributes
     * @return self
     */
    private function addRuleByTag(string $rule, array $attributes = array()): self
    {
        $class = null;
        $rule = strpos($rule, '\\') !== false ? $rule : str_replace('_', '', ucwords($rule, '_'));

        if (class_exists($rule)) {
            $class = $rule;
        } else if (class_exists('Pecee\Http\Input\ValidatorRules\ValidatorRule' . ucfirst(strtolower($rule)))) {
            $class = 'Pecee\Http\Input\ValidatorRules\ValidatorRule' . ucfirst(strtolower($rule));
        } else if (InputValidator::getCustomValidatorRuleNamespace() !== null && class_exists(InputValidator::getCustomValidatorRuleNamespace() . '\ValidatorRule' . ucfirst(strtolower($rule)))) {
            $class = InputValidator::getCustomValidatorRuleNamespace() . '\ValidatorRule' . ucfirst(strtolower($rule));
        }
        if ($class !== null && is_a($class, IInputValidatorRule::class, true)) {
            $this->rules[] = $class::make(...$attributes);
        }
        return $this;
    }

    /**
     * @param $name
     * @param $arguments
     * @return $this|InputValidatorItem
     */
    public function __call($name, $arguments)
    {
        return $this->addRuleByTag($name, $arguments);
    }
```

I would like to hear your feedback on this before I commit anything, because I don't know if the `__call()` method will bring some performance drawback or something.

**Comment by DeveloperMarius** [comment]
Hey @guiiamorim,

nice work on the camel case thing.
But then we don't have to do `ucfirst()` on the `$rule` again, because `ucwords()` creates a string starting with an upper case.
`str_replace('_', '', ucwords('starts_with', '_'));` => `StartsWith`
Also I would just call `if (class_exists($rule)) {` when `\\` is in the rule. And when the class doesn't exists, we can skip checking the other cenarios.

I have to say that I don't really get the part with the `__call()`. When and for what do you want to use it? Can you provide me with an example?

~ Marius

**Comment by guiiamorim** [comment]
Hey @DeveloperMarius,

> But then we don't have to do ucfirst() on the $rule again, because ucwords() creates a string starting with an upper case.

My bad, forgot to delete those.

> Also I would just call if (class_exists($rule)) { when \\ is in the rule. 

You're right, I actually don't need the ternary, I can just call the `str_replace('_', '', ucwords('starts_with', '_'));` on the rule. If the class is proper named it won't change anything.

> I have to say that I don't really get the part with the __call(). When and for what do you want to use it? Can you provide me with an example?

Before you had placed some methods for chainig on the class, like `max()`, `isString()`. So basically, for all the base rules that we implement, we'd have to create a method on the class for chaining. So I replaced this methods whith the [__call()](https://www.php.net/manual/en/language.oop5.overloading.php#object.call) method, wich will search for the rule and add it to the rules attribute without having to write a method for each rule. Basically, we will have the method chainig for every rule we write out of the box. Ex:

```PHP
$request->validate(
    // This will call the method __call() twice for each input, since both isString() and max() methods doesn't exists on the class
    InputValidator::make()
        ->add(InputValidatorItem::make('username')->isString()->max(50))
        ->add(InputValidatorItem::make('password')->isString()->max(20))
);
```

**Comment by DeveloperMarius** [comment]
Hey,

I think this is a great idea. But there would be no autocomplete/ static analysis hints for `InputValidatorItem` class.
I will do some thinking about that and search for a solution.

I don't know about the performance drawback, but I will look into that. 
You can create the PR and then we will discuss this further!

Great work.

~ Marius

**Comment by DeveloperMarius** [comment]
Hey, in my last commit I added a lot of stuff.
In the first step, I cleaned up the code.
After that I implemented some more rules and I think now we have all the basic ones. It would be great if you can give me feedback which we still need and if a rule is useless.
In the last step, I created requirements for rules. So before validating the rule `email` I require the rule `string` which requires `required`. Because this can get messy with large applications, I integrated a cache.
Case example:
`['textValue' => 'string|min:10|max:20']`
The rules max and min require (among other things) `string` -> 3 times `string`. String requires `required` -> 3 times `required`.
With the cache, I prevent this recursive deep dive and check when validating `min` and `max` if the value was already validated for `string` (Which in this case was when validating the first rule). So we don't have to repeat that. What do you think?

~ Marius

**Comment by guiiamorim** [comment]
Hi @DeveloperMarius ,

I'm truly sorry for disappearing for so long, I was very busy at work and didn't open github for a while. My computer came from the shop this week, so I'm all set to continue working.

> After that I implemented some more rules and I think now we have all the basic ones. It would be great if you can give me feedback which we still need and if a rule is useless.

I'll pull the code to see what rules you've implemented and will tell you if there are anything missing or even code and sent to you.

> With the cache, I prevent this recursive deep dive and check when validating min and max if the value was already validated for string (Which in this case was when validating the first rule). So we don't have to repeat that. What do you think?

I think it's a great idea, I'll have to take a look in the code to be shure but I'm a bit concerned about nullable fields. I had implemented a `nullable` rule and I don't know if the requirement of the rule required by other rules would have effect on this. I also was thinking about implementing a rule in the same form of the rule `sometimes` in Laravel, that returns true if the field isn't present in the request, but if it is present, it cant be empty/null. I don't know if this would be possible with this change (although this rule may not be necessary).

Validation aside, I was working on a project in which I'm using this package for routing, and I miss the ability to filter out inputs that I don't want in the inputHandler. Currently on the `all()` method I can filter only the fields that I want to retrieve, but if I want all fields except one, I would have to make a list of all fields that I do want (that could be up to dozens). I'm thinking of implementing this feature in this PR, and could do this only passing another parameter on the `all()` method or creating another method e.g.: `except()` on the inputHandler, what do you think?

**Comment by DeveloperMarius** [comment]
Hey,

I have to be honest.
I put some much work into the router and my PRs, but I currently don't see them merged soon.
I need a working release for my own projects. In the last weeks I pushed every idea I had into my fork (branch v5-development) and created a release from that, which also contains all bug fixes that haven't been merged yet. 
Also, as I complained in #515 and #611 the support of the router should be updated immediately, because they are not supported anymore and doesn't receive security and bug fixes.

I had some really interesting ideas for a php8 and integrated them into a separate [branch (v5-development-php8)](https://github.com/DeveloperMarius/simple-php-router/tree/v5-development-php8). 
I used PHP attributes to hint validation information and stuff to the routes. My code currently looks something like this:
```
#[
        APIRoute(Route::POST, '/user/reset-password'),
        ValidatorAttribute('old_password', 'string'),
        ValidatorAttribute('new_password', 'string'),
        ValidatorAttribute('confirm_password', 'string')
    ]
    public function resetPassword(){
        $data = $this->input()->requireAttributeValues();
        [...]
     }
```
and by calling `requireAttributeValues()` I automatically receive all inputs hinted by the `ValidatorAttribute`. Both validated and parsed. By that, I assure maximum security and type sensitivity.
I also added support for the route parameters which looks like this:
```
public function generateSepa(
        #[ValidatorAttribute('type', 'string', 'in:b2c:b2b')] string $type,
        #[ValidatorAttribute('account_owner', 'string', 'nullable')] ?string $account_owner = null,
        #[ValidatorAttribute('iban', 'string', 'nullable')] ?string $iban = null
    ){}
```
The validation is a required factor for rendering the route. So when `$type` would be an integer like `1234` the route wouldn't be rendered at all.


Then, (in my code, not in the router) I also use the attribute for defining some rules which are automatically checked before inserting into the database. I am coding using the MVC concept and my models look something like this:
```
[...]
/* @var int $id */
    #[ValidatorAttribute('id', 'int')]
    #[ReadonlyProperty]
    protected int $id;

    /* @var String $street */
    #[ValidatorAttribute('street', 'string', 'max:100')]
    protected string $street;
[...]
```
and when I then call the update or create function of my own DatabaseManager I automatically validate this inputs against the model before inserting them into the database. Again, maximum security and control over the inputs provided by the user.

If you are interested in working with me in my fork I would welcome your ideas very much! I need a working release which receives updates and improvements more often. I also want to profit from the newest updates in php and do not want to stay back in old php versions.
Which php version are you currently using? I would like to add features to the php8 branch and only bug fixes to the normal v5-development branch, because I want to stay up to date. If you are using php7 we can talk how we provide feature updates to both branches.
If you want to use my fork and also want to work with me to improve the router I can write all the changes into the README. 
By doing this I would also explain you my changes and maybe you have even better ideas!

I am currently not at home but will drive there tomorrow. Then I will create a PR where we can write more detailed, if you want to. There we can also talk about your ideas in your last comment.

Looking forward to your decision and feedback.

~ Marius

**Comment by guiiamorim** [comment]
Hi,

I was thinking about this in some time, I also need this updates for my current project and don't see this updates coming to life very soon. I would love to work with you in your fork.

I'm using PHP8 an think that developing new features to the newer versions is better, but we can discuss a way to support the older versions too so we can get users from this versions and maybe get more contributors for the project. I'll wait for your PR tomorrow then and we can start working.

**Comment by DeveloperMarius** [comment]
Hey @guiiamorim,

sorry I was very busy today. I created the [PR](https://github.com/DeveloperMarius/simple-php-router/pull/3) and will write the README tomorrow, because I have a lot of work on my desk this evening and won't have time. Feel free to write your wishes and ideas into the PR of the fork. Looking forward to that. Alternatively, wait until I update the README to get you up to date.
As a followup I will close this PR. If someone is interested in the features of this PR you can move over to my fork.
If @skipperbent has some time we can discuss with him if we should merge or work into his main project.
Until then, see you in my fork!

~ Marius

**Pull request closed without merging**
