### PR TITLE
PHPUnit file tests

### PR DESCRIPTION
**Pull request by DeveloperMarius**
Hey,

in this pull I'm creating some file tests.
This is in active development because I can't test some functions local and have to use github actions to test on a server.

~ Marius

### CODE REVIEW

**Comment by DeveloperMarius** [comment]
Hey @skipperbent,

what was your plan with the `public function testFiles()`?
I added `public function testFile()` (is working and ready for merge).
Do you have any other tests in mind?

~ Marius

**Comment by skipperbent** [comment]
It was basically what you've created. You just beat me to it. Nice work!

**Comment by skipperbent** [comment]
Maybe multiple files/array would be nice. I think it can be easily achieved by just using your existing code

**Comment by DeveloperMarius** [comment]
I will work on that tomorrow. I have some ideas^^

**Comment by skipperbent** [comment]
> I will work on that tomorrow. I have some ideas^^

Sounds good! You've made some valuable contributions to the project, so don't stress yourself. I'll wait with the merge and look and eye out for changes here.

**Pull request merged**
