### PR TITLE
Add the PHP DI

### PR DESCRIPTION
**Pull request by dracola**
@skipperbent I will try to  add the phpunit soon :)

### CODE REVIEW

**Comment by skipperbent** [comment]
@dracola great work 👌 let me know when it's ready for review 😊

**Comment by dracola** [comment]
It works fine for me So you can review it.
My next step to add Controller class,
I also inspiring laravel :smile: @skipperbent

**Comment by skipperbent** [comment]
@dracola  Great work - however this might have to be added to the next version of the library to avoid any compatibility issues people might experience due to the change in the required php-version.

**Comment by dracola** [comment]
@skipperbent No problem. that's fine

**Comment by skipperbent** [comment]
Hi @dracola ,

I haven't forgotten about you :)

Your feature will be added in the next version 4.0, once it's more stable.

/ Simon

**Comment by dracola** [comment]
@skipperbent yes no problem :+1: 
I found it has conflicts so i closed it for now.

**Comment by skipperbent** [comment]
@dracola What kind of conflicts did you find, was it a simple-router or third party conflict? 

I'll add the feature with unit tests to ensure that it won't conflict with any of the existing functionality. However I need to ensure that the new PHP 7 functionality is stable.

/ Simon

**Comment by dracola** [comment]
@skipperbent OK,
no  I mean it has merge conflicts with SimpleRouter.php

**Comment by dracola** [comment]
Also i didn't try version 4 yet!.
I'll try it soon

**Comment by skipperbent** [comment]
Ahh I see - don't worry about the merge conflicts, I'll take care of those.

You are welcome to try it out- however it requires PHP 7.1 so you will have to do some minor change to any custom Middlewares, ExceptionHandlers etc. in your project.

You can read some of the additional changes stuff here:
https://github.com/skipperbent/simple-php-router/releases/tag/4.0.0.0

Please feel free to report any bugs etc. you might encounter.

/ Simon

**Pull request closed without merging**
