### PR TITLE
[FEATURE] IP restrict access

### PR DESCRIPTION
**Pull request by skipperbent**

### CODE REVIEW

**Comment by DeveloperMarius** [comment]
Why are you now adding the feature I put into #511?

**Comment by skipperbent** [comment]
I wanted to add this PR so you could see an alternative way of implementing the feature without modifying the code in your PR.

Whitelist there if you want to allow certain ip's within a blocked range. For example block all 8.8.* ips except (8.8.1.2).

**Comment by DeveloperMarius** [comment]
Should I change my code to match your way and remove the ip block?

**Comment by skipperbent** [comment]
>Hmm, you are right with the browsers, but my intention behind this was for example to block IE or browsers that don't support a specific feature that is needed to access this site.

I know and I understand the intentions and see it's potential, but I think people will get a lot greater results by adding a third party library that does the job is to track browsers much better and are regularly updated.

>The pro of my method is that you can add this restriction to a specific route and to a group. With your method you have to create a group and middleware for that.

I agree it's a bit more limited in that regard. But I think most people will use restrictions on multiple pages like an administration-area etc. It also ensures, that the code is not rendered for 99% of people that won't use the feature as speed is the #1 priority of the framework.

>I think of this restriction more like the ->where() function and not as a middleware.

Maybe it should all be moved to a separate type of route. Like some kind of `AuthRoute`. That way the code will only be rendered when people use this specific type of route and the code will be separated and not spread across multiple classes.

Or maybe there's an even better way we just haven't thought about.

**Comment by DeveloperMarius** [comment]
Hmm, okay. 
I think the same problem you have with the regex for the browsers you also will have with the Plattform regex.
I think I should change my restricted access to add a User-Agent Middleware where the developer sets a regex that is matched with the User-Agent?
Also I know what you mean with third party regex library. What do you think about, when we add a base library for User-Agent parsing which can be extended/ changed using a third party library, If the developer wants custom regex or different checks? So we provide a sample that workes but don't have to be used. Like the CsrfVerifier.

All in all I think there are no more ways to add that. The best way is to provide multiple Middleware examples/ bases that the developers can use but don't have to use. 
I will change my pull to a User-Agent Middleware and add some logic to it. I will also provide a sample for Plattform and browser parsing, like the current csrf system, that can be used but don't have to be used.

What do you think about that?

**Comment by DeveloperMarius** [comment]
As addition, I wouldn't add another route type. I think there was enough confusion with the current two group types. Let's try it using Middlewares.

**Comment by skipperbent** [comment]
>Also I know what you mean with third party regex library. What do you think about, when we add a base library for User-Agent parsing which can be extended/ changed using a third party library, If the developer wants custom regex or different checks? So we provide a sample that workes but don't have to be used. Like the CsrfVerifier.

That's a great idea! Then we won't be in a situation where we constantly have to change it to fit the ever changing needs. And people can use whatever framework that floats their boat. 

>As addition, I wouldn't add another route type. I think there was enough confusion with the current two group types. Let's try it using Middlewares.

Yeah you have a great point, but the route is a great way of separating logic. But I see what you mean, plus if I wanted a resource-controller route that had auth the `AuthRoute` features, then we'd have to add special `AuthRoute` types for each route-type `AuthResourceRoute` etc and that would suck.

The explanation of the `partialGroup` in the documentation was unclear. I've updated the documentation as there's a real difference in how it behaves, I was just confused myself until I read the code.

**Pull request merged**
