### PR TITLE
Add response methods for api routes

### PR DESCRIPTION
**Pull request by DeveloperMarius**
Hey,

I know not everyone handles/ prints an api response like this, but when I speak for myself I would love to use these methods, because it really minifys my code and kind of forces/ gives me the oppotunity to return `errors` and response `codes` to my frontend.
I currently have to write "a lot" of code to setup the structure for my json error and success response. This could help a lot!

I also added a small check if the json is encoded properly.

What do you think?

~ Marius

### CODE REVIEW

**Comment by skipperbent** [comment]
While i understand what you are trying to achieve, I think it's the wrong approach. The `Response` class job is to handle the response, not the output - that should be up to the project.

If you want to simplify your code, I would suggest you restructured it as there's already ways you can do just that. 
Here's the approach I use:

1. In your `routes.php` wrap all your /api/ calls in a group and set a custom exception handler, like so:

```php
Router::group(['exceptionHandler' => ApiExceptionHandler::class], function() {
    // your api routes here
});
```

2. In your `ApiExceptionHandler` class output the error in your desired format (note: you can create and throw custom exceptions to pass more data).

```php
class ApiExceptionHandler implements IExceptionHandler
{
	public function handleError(Request $request, \Exception $error): void
	{
                 // Log error
                 Logger::log($error);

                 // Display error
		response()->json([
                      'error' => $error->getMessage(),
                      'code' => $error->getCode(),
                 ]);
	}

}
```

3. In your api-controller, make sure to throw exceptions when errors occurs.

4. If you need custom formatting in your api-controllers, you can create an abstract `ApiController` class that contains methods that parse the output correctly. For example:

```php
abstract class ApiController {

     public function json(array $data) {
           // your special formatting
           response()->json([
               'data' => $data,
           ]);
     }

}
```

Your api-controller classes:

```php
class ApiUser extends ApiController {

    public function getUser($userId) {
         // do stuff
         $user = User::firstOrFail($userId);
         $this->json($user);
    }

}
```

Hope it makes sense.

/ Simon

**Comment by DeveloperMarius** [comment]
Hmm, I know what you mean when you say that the response class should not handle the output, but I thought it would be useful and these functions are really justi doing a small output handle.
I already use a similar approach with an ExceptionHandler but I don't want to create an special exception for everything and also don't want to throw just a normal exception. When you think that this is the wrong place, I will integrate these functions into my controller base file which I extend to every controller.

~ Marius

**Comment by skipperbent** [comment]
You can also take a look at Traits. I use them for mundane things that gets repeated over and over. 

```php
trait JsonResponse {
   public function formatJson(array $data) {
       // your magic
   }
}
```

```php
class ApiController {

   use JsonResponse;

   public function getUser($userId) {
         // do stuff
         $user = User::firstOrFail($userId);
         $this->formatJson($user);
   }

}

**Comment by DeveloperMarius** [comment]
Hmm, but where is there a difference between a trait and just extending a class which includes all basic methods like I do it currently?

**Comment by skipperbent** [comment]
> Hmm, I know what you mean when you say that the response class should not handle the output, but I thought it would be useful and these functions are really justi doing a small output handle.
> I already use a similar approach with an ExceptionHandler but I don't want to create an special exception for everything and also don't want to throw just a normal exception. When you think that this is the wrong place, I will integrate these functions into my controller base file which I extend to every controller.
> 
> I just thought it would be easier to just add these methods there so no one have to create them themself.
> 
> ~ Marius

You can just throw a basic `\ErrorException` with the message & error-code when doing your validation and pick it up by your ExceptionHandler.

```php
   public function getUser($userId) {
         // do stuff
         if(\is_int($userId)) {
             throw new \ErrorException('Invalid user-id', 2);
         }
   }
```

> Hmm, but where is there a difference between a trait and just extending a class which includes all basic methods like I do it currently?

You can inject them into classes that's already extended. I rarely use them, only for things that are repeated often but are too small to need it's own class. It's like injecting helper methods, but the idea is the same. But it can easily become confusing because it can seem like things happen "in the dark". Extending is the best method in my opinion.

**Comment by DeveloperMarius** [comment]
Okay, I will close this issue.

**Comment by skipperbent** [comment]
An example where traits are smart is that you can have a trait that change the behavior of your class. For instance your middleware could be blocking browsers or authenticating. Then when you needed that specific behavior, you just called `use BrowserBlocker, UserAuth` etc... you get the idea

**Comment by skipperbent** [comment]
I will go over your pull requests in debt when I get some more time like before. I think I'm almost ready to release v4, so i will be closing and monitoring the issues when the release go live.

**Comment by DeveloperMarius** [comment]
Yes I think the rest of the Issues will not be answert in the next time...
Everything I wanted to include to the next release is merged.
The rest of my pull requests are for the next major update.
Yes, it would be nice if you can go over it. The comments really helped me 👍🏻.
You don't have to look over the `restricted access` pull. I have to work on that a bit deeper and more. The rest would be really nice.

~ Marius

**Pull request closed without merging**
